#cloud-config
package_update: true
package_upgrade: true

packages:
  - wget

runcmd:
  # download and run vpn setup script
  - wget -4 https://git.io/vpnsetup -O vpnsetup.sh
  - sed -i "s|^YOUR_IPSEC_PSK=''|YOUR_IPSEC_PSK='${vpn_psk}'|" vpnsetup.sh
  - sed -i "s|^YOUR_USERNAME=''|YOUR_USERNAME='${vpn_username}'|" vpnsetup.sh
  - sed -i "s|^YOUR_PASSWORD=''|YOUR_PASSWORD='${vpn_password}'|" vpnsetup.sh
  - bash vpnsetup.sh
